services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abrhernandez
      - MONGO_INITDB_ROOT_PASSWORD=abrhernandez
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
    - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=abrhernandez
      - ME_CONFIG_MONGODB_ADMINPASSWORD=abrhernandez
      - ME_CONFIG_MONGODB_SERVER=mongodb